server:
  port: 8089

spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/live?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


security:
  oauth2:
    client:
      client-id: line-client
      access-token-uri: http://localhost:8089/oauth/token
      user-authorization-uri: http://localhost:8089/oauth/authorize
      scope: app
      client-secret: secret
      grant-type: password
      use-current-uri: false
      pre-established-redirect-uri: http://localhost:8089/authorized

    resource:
      jwk:
        key-set-uri: http://localhost:8089/oauth2/keys

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, env, metrics